server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dannyaj/spring-cloud-config-repo      # 配置Git仓库的地址
          username:                                                         # Git仓库的账号
          password:                                                         # Git仓库的密码
          
# http://127.0.0.1:8080/microservice-foo-dev.properties
# http://127.0.0.1:8080/microservice-foo-dev.yml
# http://peer1:8080/microservice-foo/dev

# refer ebook page 147