server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://user:password@peer1:8761/eureka/,http://user:password@peer2:8762/eureka/
      #defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    
# 禁用filter
# zuul.SendResponseFilter.pre.disable=true
# zuul.SendResponseFilter.post.disable=true

    
# refer ebook page 125, 127, 129