server:
  port: 8000
spring:
  h2:
    console:
      enabled: true
  application:
    name: microservice-provider-user # register into eureka server display name
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    platform: h2                        # 指定数据源类型
    schema: classpath:schema.sql        # 指定h2数据库的建表脚本
    data: classpath:data.sql            # 指定h2数据库的数据脚本
logging:                                # 配置日志级别，让hibernate打印出执行的SQL
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@peer1:8761/eureka/,http://user:password@peer2:8762/eureka/
      #defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
      #defaultZone: http://127.0.0.1:8761/eureka/
    #healthcheck:
    #  enabled: true
  instance:
    prefer-ip-address: true # 表示將自己的ip 注冊到eureka server, 如設成false, 表示所操作系統的hostname 到 eureka server