server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dannyaj/spring-cloud-config-repo     # 配置Git仓库的地址
          username:                                                         # Git仓库的账号
          password:                                                         # Git仓库的密码
        health:
          repositories:
            a-foo: 
              label: master
              name: microservice-foo
              profiles: dev
              
# refer ebook page 155
# http://127.0.0.1:8080/health