server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@peer1:8761/eureka/,http://user:password@peer2:8762/eureka/
      #defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      max-file-size: 2000Mb      # Max file size，默认1M
      max-request-size: 2500Mb   # Max request size，默认10M
      
  
      
# refer ebook page 123      
# 直接上傳 refer curl -F "file=@microservice-provider-user-0.0.1-SNAPSHOT.jar" 127.0.0.1:8050/upload

# 測試通過 zuul 上傳小文件
# curl -v -H "Transfer-Encoding: chunked" -F "file=@microservice-provider-user-8001.sh" 127.0.0.1:8040/microservice-file-upload/upload

# 測試通過 zuul 上傳大文件, 不加/zuul 
# curl -v -H "Transfer-Encoding: chunked" -F "file=@microservice-provider-user-0.0.1-SNAPSHOT.jar" 127.0.0.1:8040/microservice-file-upload/upload

# 測試通過 zuul 上傳大文件, 加/zuul 
# curl -v -H "Transfer-Encoding: chunked" -F "file=@microservice-provider-user-0.0.1-SNAPSHOT.jar" 127.0.0.1:8040/zuul/microservice-file-upload/upload
 