server:
  port: 8010
spring:
  application:
    name: microservice-hystrix-turbine
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://user:password@peer1:8761/eureka/,http://user:password@peer2:8762/eureka/
      #defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
