server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dannyaj/spring-cloud-config-repo      # 配置Git仓库的地址
          username:                                                         # Git仓库的账号
          password:                                                         # Git仓库的密码
    bus:
      trace:
        enabled: true     # 开启cloud bus的跟踪
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    
# refer ebook page 163

# 1. 啟動 microservice-config-server-refresh-cloud-bus
# 2. 啟動 microservice-config-client-refresh-cloud-bus
# 3. 將 microservice-config-client-refresh-cloud-bus port 改8082 , 再啟動一個
# 4. 訪問 http://127.0.0.1:8081/profile , 未更新
# 5. 訪問 http://127.0.0.1:8082/profile , 未更新
# 6. 將 git repository 中的 microservic-foo-dev.properties 文件更改 profile=dev-1.0-cloud-bus
# 7. post curl -X POST http://127.0.0.1:8080/bus/refresh
# 8. http://127.0.0.1:8080/trace
# 9. 訪問 http://127.0.0.1:8081/profile
# 10. 訪問 http://127.0.0.1:8082/profile
